// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifnbhibvintdjgschvuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbmJoaWJ2aW50ZGpnc2NodnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjQzMjcsImV4cCI6MjA1NTY0MDMyN30.CIk4G4XjMy0IsK0WVeMB1vEt4GrY1_UKzQoqu2n2BTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);